// @generated by tauri-specta — run `just bindings` to regenerate.
/* eslint-disable */
// prettier-ignore

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Liveness check. Returns a greeting plus the backend version.
	 * 
	 *  `name` is rejected when blank so the frontend has a real error path to render
	 *  against before any milestone-1 command exists.
	 */
	ping: (name: string) => typedError<Pong, IpcError>(__TAURI_INVOKE("ping", { name })),
	/**  Return [`AppInfo`]. Everything is a compile-time constant. */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**
	 *  The real component catalog, merged with real installed state — what the Dependencies screen
	 *  renders.
	 */
	listComponents: () => typedError<ComponentInfo[], IpcError>(__TAURI_INVOKE("list_components")),
	/**
	 *  Run the real `bootstrap()` (task 0012) for every M1 component still missing, reporting
	 *  progress on `job://bootstrap` as it goes.
	 */
	bootstrapToolchain: () => typedError<null, IpcError>(__TAURI_INVOKE("bootstrap_toolchain")),
	/**
	 *  Install a **single** SDK component by its `sdkmanager` package path (`ComponentInfo.id`, e.g.
	 *  `platform-tools`). Same `job://bootstrap` progress channel as [`bootstrap_toolchain`] — only
	 *  one such job runs at a time. A component that's already installed is a clean no-op.
	 */
	installComponent: (componentId: string) => typedError<null, IpcError>(__TAURI_INVOKE("install_component", { componentId })),
	/**
	 *  Remove a **single** app-managed SDK component — the mirror of [`install_component`], running
	 *  `sdkmanager --uninstall <id>`. `cmdline-tools` can't be removed here (it's the uninstaller
	 *  itself), and a component that lives in an existing system SDK is left untouched. Fast enough
	 *  that it needs no progress stream: the caller re-reads [`list_components`] afterwards.
	 */
	uninstallComponent: (componentId: string) => typedError<null, IpcError>(__TAURI_INVOKE("uninstall_component", { componentId })),
	/**  Every Google device profile, parsed from the installed `sdklib` jar. */
	listDevices: () => typedError<DeviceInfo[], IpcError>(__TAURI_INVOKE("list_devices")),
	/**
	 *  Today's real system-image catalog (Google's per-tag `sys-img2-3.xml` manifests), merged with
	 *  local install state.
	 */
	listImages: () => typedError<ImageInfo[], IpcError>(__TAURI_INVOKE("list_images")),
	/**  Every registry-tracked emulator with its live state — what the Dashboard polls. */
	listEmulators: () => typedError<EmulatorInfo[], IpcError>(__TAURI_INVOKE("list_emulators")),
	/**
	 *  Reconcile the registry against on-disk / adb reality, then return the refreshed list. The
	 *  Dashboard's "Refresh" action and a manual recovery from drift.
	 */
	reconcileNow: () => typedError<EmulatorInfo[], IpcError>(__TAURI_INVOKE("reconcile_now")),
	/**
	 *  Ensure the chosen image is installed, create the AVD, optionally launch it. Streams progress
	 *  on `job://emulator` with `jobId` `create:<avdName>`. Returns the new tracked id.
	 */
	createEmulator: (request: CreateEmulatorRequest) => typedError<string, IpcError>(__TAURI_INVOKE("create_emulator", { request })),
	/**
	 *  Launch an already-created emulator and wait for it to boot. Streams on `job://emulator` with
	 *  `jobId` `launch:<id>`.
	 */
	launchEmulator: (id: string) => typedError<null, IpcError>(__TAURI_INVOKE("launch_emulator", { id })),
	/**
	 *  Stop a running emulator: graceful `adb emu kill`, then force-kill the held child if it doesn't
	 *  exit (the shared provider means that held handle now actually persists — task 0020).
	 */
	stopEmulator: (id: string) => typedError<null, IpcError>(__TAURI_INVOKE("stop_emulator", { id })),
	/**  Rename a tracked emulator (display name only — the on-disk AVD name never changes). */
	renameEmulator: (id: string, displayName: string) => typedError<null, IpcError>(__TAURI_INVOKE("rename_emulator", { id, displayName })),
	/**
	 *  Update an emulator's stored RAM / storage / graphics. Recorded now; applied when the AVD is next
	 *  (re)created — see `AndroidProvider::set_hardware`.
	 */
	editHardware: (id: string, ramMb: number, storageMb: number, graphics: string, deviceFrame: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("edit_hardware", { id, ramMb, storageMb, graphics, deviceFrame })),
	/**
	 *  Delete a tracked emulator. `wipe` also removes the AVD from disk (`avdmanager delete avd`);
	 *  `wipe = false` just untracks it.
	 */
	deleteEmulator: (id: string, wipe: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("delete_emulator", { id, wipe })),
	/**
	 *  Wipe an emulator's user data (deletes the AVD's writable images + snapshots; next launch
	 *  rebuilds them). Refuses while running.
	 */
	wipeEmulatorData: (id: string) => typedError<null, IpcError>(__TAURI_INVOKE("wipe_emulator_data", { id })),
	/**  Full detail for one emulator — its stored config plus live run state. */
	emulatorDetail: (id: string) => typedError<EmulatorDetail, IpcError>(__TAURI_INVOKE("emulator_detail", { id })),
	/**
	 *  The tail of an emulator's launch log — history for the detail-panel console. Live lines arrive
	 *  separately on `job://emulator`. Empty (not an error) when it's never been launched.
	 */
	emulatorLogTail: (id: string, maxLines: number) => typedError<string[], IpcError>(__TAURI_INVOKE("emulator_log_tail", { id, maxLines })),
	/**  Reveal a path in the OS file manager (Finder / Explorer / the default file browser). */
	revealPath: (path: string) => typedError<null, IpcError>(__TAURI_INVOKE("reveal_path", { path })),
	/**  Parse + validate + resolve a dropped `.emuprofile` into a preview. */
	inspectProfile: (bytes: number[]) => typedError<ProfileInspection, IpcError>(__TAURI_INVOKE("inspect_profile", { bytes })),
	/**
	 *  Import a `.emuprofile`: ensure its image, create the AVD as `Imported`, optionally launch.
	 *  Streams on `job://emulator` with `jobId` `apply:<avdName>`. Returns the new tracked id.
	 */
	applyProfile: (bytes: number[], launch: boolean) => typedError<string, IpcError>(__TAURI_INVOKE("apply_profile", { bytes, launch })),
	/**  The tracked emulator `id` as a pretty-printed `.emuprofile` JSON string (for the clipboard). */
	exportProfile: (id: string) => typedError<string, IpcError>(__TAURI_INVOKE("export_profile", { id })),
	/**
	 *  Write the tracked emulator `id` as an `.emuprofile` file at `path` — the location the user
	 *  picked in the native Save dialog (`@tauri-apps/plugin-dialog`'s `save()`). The mirror of the
	 *  Profiles screen's drag-in import.
	 */
	exportProfileToPath: (id: string, path: string) => typedError<null, IpcError>(__TAURI_INVOKE("export_profile_to_path", { id, path })),
	/**  Validate and save a `.emuprofile` to the local list (keyed by its `name`). */
	saveProfile: (bytes: number[]) => typedError<null, IpcError>(__TAURI_INVOKE("save_profile", { bytes })),
	/**  Every saved profile, newest first. */
	listProfiles: () => typedError<ProfileSummary[], IpcError>(__TAURI_INVOKE("list_profiles")),
	/**  The JSON body of a saved profile — for "Apply" of a saved entry (feed it back to `apply_profile`). */
	getSavedProfile: (name: string) => typedError<string, IpcError>(__TAURI_INVOKE("get_saved_profile", { name })),
	/**  Delete a saved profile. */
	deleteProfile: (name: string) => typedError<null, IpcError>(__TAURI_INVOKE("delete_profile", { name })),
	/**  Probe the machine for emulator readiness. Also records a `host_snapshots` row (best-effort). */
	probeHost: () => typedError<HostReportDto, IpcError>(__TAURI_INVOKE("probe_host")),
	/**  Run a scriptable host fix with OS elevation and return `emu-helper`'s structured outcome. */
	runHelper: (fixId: string) => typedError<HelperOutcomeDto, IpcError>(__TAURI_INVOKE("run_helper", { fixId })),
	/**
	 *  Start streaming `adb logcat` for a running emulator. Lines arrive on `device://log`; the
	 *  stream stops on [`stop_logcat`], on app exit, or when the device goes away.
	 */
	startLogcat: (id: string) => typedError<null, IpcError>(__TAURI_INVOKE("start_logcat", { id })),
	/**  Stop the `adb logcat` stream for `id`. Idempotent — a no-op if none is running. */
	stopLogcat: (id: string) => typedError<null, IpcError>(__TAURI_INVOKE("stop_logcat", { id })),
	/**  Model / Android version / battery / `/data` usage for a running emulator. */
	deviceFacts: (id: string) => typedError<DeviceFactsDto, IpcError>(__TAURI_INVOKE("device_facts", { id })),
	/**
	 *  Interface addresses + open sockets of a running emulator (socket-level, IPv4 — this is not an
	 *  HTTP inspector; that needs an in-app agent Emulator Studio doesn't inject).
	 */
	deviceNetwork: (id: string) => typedError<DeviceNetworkDto, IpcError>(__TAURI_INVOKE("device_network", { id })),
	/**  Write a redacted diagnostics zip to `<data_dir>/diagnostics-<unix-ts>.zip`. */
	exportDiagnostics: () => typedError<string, IpcError>(__TAURI_INVOKE("export_diagnostics")),
};

/** Events */
export const events = {
	deviceLog: makeEvent<DeviceLogLine>("device://log"),
	jobBootstrap: makeEvent<BootstrapProgress>("job://bootstrap"),
	jobEmulator: makeEvent<EmulatorJob>("job://emulator"),
};

/* Types */
/**
 *  Static app metadata for the About screen — version, licence, repo, and a one-line-per-feature
 *  summary. No I/O.
 */
export type AppInfo = {
	name: string,
	/**  `CARGO_PKG_VERSION`. */
	version: string,
	/**  `CARGO_PKG_LICENSE` — `"UNLICENSED"` today; a real OSS licence is M7's `LICENSE`-chosen line. */
	license: string,
	repository: string,
	description: string,
	/**  One short line per headline feature. */
	features: string[],
};

/**  Live progress for a `bootstrap_toolchain` run, emitted as `job://bootstrap`. */
export type BootstrapProgress = {
	/**
	 *  Always [`JOB_ID`] today — carried on the payload anyway so the frontend never has to know
	 *  that, and so a future real job registry is a backward-compatible change, not a breaking one.
	 */
	jobId: string,
	payload: BootstrapProgressKind,
};

/**
 *  One update from a `bootstrap_toolchain` run. Mirrors `docs/architecture.md` §4's
 *  `job://progress`/`job://log`/`job://done` shapes, collapsed into one typed event (there is only
 *  ever one toolchain-bootstrap job at a time — a real per-job registry is M3's "Registry &
 *  reliable tracking" milestone, not needed here).
 */
export type BootstrapProgressKind = 
/**  A phase and/or percentage update. */
{ type: "progress"; phase: string | null; pct: number | null } | 
/**  One log line to append to the run's tail. */
{ type: "log"; line: string } | 
/**  The job reached a terminal state. */
{ type: "done"; ok: boolean; error: IpcError | null };

/**
 *  One component as shown on the Dependencies screen: catalog info merged with real install
 *  state (`installed`/`source` come from `emu_core::toolchain::InstalledState`, scanned fresh on
 *  every call — never cached, per the same rule `SystemImage::installed` follows).
 */
export type ComponentInfo = {
	/**  The exact `sdkmanager` package path (`ComponentId::repo_path`) — a stable id. */
	id: string,
	/**  Human-readable label for the UI. */
	name: string,
	/**  Package revision from the catalog. */
	version: string,
	/**
	 *  Archive size in bytes. `u32` (not the catalog's `u64`) because specta-typescript refuses
	 *  to export a bigint-risking `u64` to a plain JS `number` — every real M1 archive is well
	 *  under 4 GiB, and even `docs/spec.md`'s largest future system images (~3.5 GB) fit, so this
	 *  is a safe, deliberate narrowing, saturating at `u32::MAX` in the (currently impossible)
	 *  case of something bigger.
	 */
	sizeBytes: number,
	/**  Whether it's installed anywhere (the app's managed `sdk/` dir, or an existing system SDK). */
	installed: boolean,
	/**  Where it was found — `"app-managed"` or `"system:<path>"` — `None` when not installed. */
	source: string | null,
};

/**  Request body for [`create_emulator`]. */
export type CreateEmulatorRequest = {
	/**  Display name; the on-disk AVD name is a sanitized version of it. */
	name: string,
	/**  `DeviceInfo.id`. */
	deviceId: string,
	/**  `ImageInfo.coord`. */
	imageCoord: string,
	ramMb: number,
	storageMb: number,
	/**  Draw the device frame/bezel when this emulator launches (uses the device profile's skin). */
	deviceFrame: boolean,
	/**  Also launch it once created ("Create & launch"). */
	launch: boolean,
};

/**  A quick snapshot of a running emulator for the inspector's facts strip. */
export type DeviceFactsDto = {
	model: string | null,
	androidRelease: string | null,
	sdkInt: number | null,
	batteryPct: number | null,
	/**  Free space on `/data`, MB. */
	dataFreeMb: number | null,
	/**  Total size of `/data`, MB. */
	dataTotalMb: number | null,
};

/**  A hardware profile for the Create wizard's device step. */
export type DeviceInfo = {
	/**  `avdmanager -d` id, e.g. `pixel_6`. */
	id: string,
	/**  Human name, e.g. `Pixel 6`. */
	name: string,
	/**  Manufacturer label; empty when unknown. */
	oem: string,
	/**  `phone` / `tablet` / `foldable` / `wear` / `tv` / `automotive` / `desktop`. */
	formFactor: string,
	/**  Manufacturer-recommended RAM in MiB. */
	ramMb: number,
	/**  `"<width> × <height>"` in pixels. */
	resolution: string,
	/**  Screen density in dpi. */
	densityDpi: number,
	/**  Physical diagonal in inches. */
	diagonalIn: number | null,
	/**
	 *  Device-frame skin name (`<d:skin>`), when the profile declares one — the bezel the
	 *  emulator can draw around the screen. `None` = no dedicated frame for this device.
	 */
	skin: string | null,
};

/**
 *  One line of a running emulator's `adb logcat`, emitted as `device://log`. The frontend filters
 *  by `id` and parses the `-v threadtime` line itself (level / tag / message).
 */
export type DeviceLogLine = {
	/**  The tracked emulator id this line belongs to. */
	id: string,
	/**  The raw logcat line, or a synthetic `— … —` marker when the stream ends. */
	line: string,
};

/**  Live network state of a running emulator. */
export type DeviceNetworkDto = {
	interfaces: NetInterfaceDto[],
	connections: NetConnectionDto[],
};

/**  Full config + live state for the detail panel. */
export type EmulatorDetail = {
	id: string,
	avdName: string,
	displayName: string,
	deviceProfileId: string,
	/**  `sdkmanager` package path, when known. */
	imageCoord: string | null,
	/**  Android API level from the image coord, when known. */
	api: number | null,
	hasPlayStore: boolean,
	ramMb: number,
	storageMb: number,
	/**  `auto` / `host` / `swiftshader`. */
	graphics: string,
	/**  Whether the emulator launches with a device frame/bezel drawn around the screen. */
	deviceFrame: boolean,
	/**  `created here` / `adopted` / `from profile` / `imported`. */
	source: string,
	/**  Live: `stopped` / `booting` / `running` / `error`. */
	state: string,
	adbSerial: string | null,
	/**  RFC 3339. */
	createdAt: string,
	/**  RFC 3339. */
	updatedAt: string,
	/**  `<avd home>/<avd_name>.avd`, for the "Open folder" button. `None` if the home can't be resolved. */
	avdPath: string | null,
};

/**  A tracked emulator plus its live run state. */
export type EmulatorInfo = {
	id: string,
	avdName: string,
	displayName: string,
	/**  `stopped` / `booting` / `running` / `error`. */
	state: string,
	adbSerial: string | null,
};

/**  Live progress for an emulator create/launch run, emitted as `job://emulator`. */
export type EmulatorJob = {
	/**  `create:<avdName>` or `launch:<id>` — the frontend filters its progress panel by this. */
	jobId: string,
	payload: EmulatorJobKind,
};

/**
 *  One update from a `create_emulator`/`launch_emulator` run. Same tagged shape as
 *  `toolchain::BootstrapProgressKind` (`docs/architecture.md` §4's `job://*` events, collapsed);
 *  the `jobId` on [`EmulatorJob`] says which run it belongs to.
 */
export type EmulatorJobKind = 
/**  A phase and/or percentage update. */
{ type: "progress"; phase: string | null; pct: number | null } | 
/**  One log line to append to the run's tail. */
{ type: "log"; line: string } | 
/**  The run reached a terminal state. */
{ type: "done"; ok: boolean; error: IpcError | null };

/**  The parsed result of one elevated `emu-helper` run. */
export type HelperOutcomeDto = {
	command: string,
	/**  `ok` / `failed` / `notApplicable` / `needsReboot`. */
	status: string,
	message: string,
	needsReboot: boolean,
};

/**  One remediation from the host report. */
export type HostFixDto = {
	id: string,
	title: string,
	/**  `true` when `run_helper(id)` can perform it (with elevation). */
	scriptable: boolean,
	needsReboot: boolean,
	description: string,
};

/**  The host-readiness picture for the Dependencies screen. */
export type HostReportDto = {
	os: string,
	arch: string,
	/**  `enabled` / `disabledInFirmware` / `unknown`. */
	virtualization: string,
	/**  `kvm` / `whpx` / `aehd` / `hvf` / `none`. */
	acceleratorKind: string,
	/**  `ok` / `missing` / `noPermission` / `disabled` / `unknown`. */
	acceleratorStatus: string,
	/**  Free space on the data volume, in MB (`u32` — specta won't export a bigint-risking `u64`). */
	diskFreeMb: number,
	/**  Total RAM in MB. */
	ramMb: number,
	/**  `canAccelerate` / `degraded` / `cannotRun`. */
	verdict: string,
	/**  The `degraded` / `cannotRun` reason; empty for `canAccelerate`. */
	verdictReason: string,
	fixes: HostFixDto[],
};

/**  A system image for the Create wizard's image step. */
export type ImageInfo = {
	/**  `sdkmanager` package path — the id passed back to `create_emulator`. */
	coord: string,
	/**  Android API level. */
	api: number,
	/**  Marketing Android version, e.g. `"14"`. */
	androidVersion: string,
	/**  `default` / `google_apis` / `google_apis_playstore` / … */
	imageType: string,
	/**  `x86_64` / `arm64-v8a` / … */
	abi: string,
	/**  Package revision. */
	revision: string,
	/**
	 *  Archive size in bytes — `u32` (specta won't export a bigint-risking `u64`; every real
	 *  image is well under 4 GiB), saturating.
	 */
	downloadSizeBytes: number,
	/**  Whether it's already installed in the managed SDK. */
	installed: boolean,
	/**  Whether it bundles the Play Store. */
	hasPlayStore: boolean,
};

/**  Serializable error surfaced to the frontend across the typed IPC seam. */
export type IpcError = {
	/**
	 *  Stable machine-readable code, e.g. `not_found`, `process_failed`.
	 *  Sourced from [`emu_core::CoreError::code`] when the origin is a core error.
	 */
	code: string,
	/**  Human-facing description of what went wrong and, where possible, what to do. */
	message: string,
	/**
	 *  Optional structured context (paths, exit codes, offending values).
	 *  Exported to TypeScript as `unknown` — `serde_json::Value` carries
	 *  arbitrary JSON and specta will not emit its BigInt-bearing `Number`.
	 */
	details: unknown,
};

/**  One open IPv4 socket for the inspector's Network panel. */
export type NetConnectionDto = {
	/**  `tcp` / `udp`. */
	proto: string,
	local: string,
	remote: string,
	/**  TCP state; empty for UDP. */
	state: string,
	uid: number,
	package: string | null,
};

/**  One network interface address for the inspector's Network panel. */
export type NetInterfaceDto = {
	name: string,
	/**  e.g. `10.0.2.16/24`. */
	addr: string,
};

/**  Reply from [`ping`]. Proves the Rust↔TS seam and version wiring are live. */
export type Pong = {
	/**  Greeting echoing the caller's `name`. */
	message: string,
	/**  The running backend's crate version (`CARGO_PKG_VERSION`). */
	version: string,
};

/**  The preview shown before "Apply". */
export type ProfileInspection = {
	name: string,
	description: string,
	deviceLabel: string,
	imageLabel: string,
	/**  `sdkmanager` package path of the system image the recipe needs. */
	imageCoord: string,
	requirements: ProfileRequirement[],
	totalDownloadBytes: number,
	/**  `true` when nothing needs downloading — Apply is a straight create. */
	ready: boolean,
};

/**  One line of the import requirement table. */
export type ProfileRequirement = {
	label: string,
	/**  `true` when already installed locally. */
	present: boolean,
	/**  Bytes to download when not present (0 when present or unknown), saturating `u32`. */
	downloadBytes: number,
};

/**  One saved recipe in the list. */
export type ProfileSummary = {
	name: string,
	description: string,
	/**  RFC 3339. */
	createdAt: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

