// @generated by tauri-specta — run `just bindings` to regenerate.
/* eslint-disable */
// prettier-ignore

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Liveness check. Returns a greeting plus the backend version.
	 * 
	 *  `name` is rejected when blank so the frontend has a real error path to render
	 *  against before any milestone-1 command exists.
	 */
	ping: (name: string) => typedError<Pong, IpcError>(__TAURI_INVOKE("ping", { name })),
	/**
	 *  The real component catalog, merged with real installed state — what the Dependencies screen
	 *  renders.
	 */
	listComponents: () => typedError<ComponentInfo[], IpcError>(__TAURI_INVOKE("list_components")),
	/**
	 *  Run the real `bootstrap()` (task 0012) for every M1 component still missing, reporting
	 *  progress on `job://bootstrap` as it goes.
	 */
	bootstrapToolchain: () => typedError<null, IpcError>(__TAURI_INVOKE("bootstrap_toolchain")),
};

/** Events */
export const events = {
	jobBootstrap: makeEvent<BootstrapProgress>("job://bootstrap"),
};

/* Types */
/**  Live progress for a `bootstrap_toolchain` run, emitted as `job://bootstrap`. */
export type BootstrapProgress = {
	/**
	 *  Always [`JOB_ID`] today — carried on the payload anyway so the frontend never has to know
	 *  that, and so a future real job registry is a backward-compatible change, not a breaking one.
	 */
	jobId: string,
	payload: BootstrapProgressKind,
};

/**
 *  One update from a `bootstrap_toolchain` run. Mirrors `docs/architecture.md` §4's
 *  `job://progress`/`job://log`/`job://done` shapes, collapsed into one typed event (there is only
 *  ever one toolchain-bootstrap job at a time — a real per-job registry is M3's "Registry &
 *  reliable tracking" milestone, not needed here).
 */
export type BootstrapProgressKind = 
/**  A phase and/or percentage update. */
{ type: "progress"; phase: string | null; pct: number | null } | 
/**  One log line to append to the run's tail. */
{ type: "log"; line: string } | 
/**  The job reached a terminal state. */
{ type: "done"; ok: boolean; error: IpcError | null };

/**
 *  One component as shown on the Dependencies screen: catalog info merged with real install
 *  state (`installed`/`source` come from `emu_core::toolchain::InstalledState`, scanned fresh on
 *  every call — never cached, per the same rule `SystemImage::installed` follows).
 */
export type ComponentInfo = {
	/**  The exact `sdkmanager` package path (`ComponentId::repo_path`) — a stable id. */
	id: string,
	/**  Human-readable label for the UI. */
	name: string,
	/**  Package revision from the catalog. */
	version: string,
	/**
	 *  Archive size in bytes. `u32` (not the catalog's `u64`) because specta-typescript refuses
	 *  to export a bigint-risking `u64` to a plain JS `number` — every real M1 archive is well
	 *  under 4 GiB, and even `docs/spec.md`'s largest future system images (~3.5 GB) fit, so this
	 *  is a safe, deliberate narrowing, saturating at `u32::MAX` in the (currently impossible)
	 *  case of something bigger.
	 */
	sizeBytes: number,
	/**  Whether it's installed anywhere (the app's managed `sdk/` dir, or an existing system SDK). */
	installed: boolean,
	/**  Where it was found — `"app-managed"` or `"system:<path>"` — `None` when not installed. */
	source: string | null,
};

/**  Serializable error surfaced to the frontend across the typed IPC seam. */
export type IpcError = {
	/**
	 *  Stable machine-readable code, e.g. `not_found`, `process_failed`.
	 *  Sourced from [`emu_core::CoreError::code`] when the origin is a core error.
	 */
	code: string,
	/**  Human-facing description of what went wrong and, where possible, what to do. */
	message: string,
	/**
	 *  Optional structured context (paths, exit codes, offending values).
	 *  Exported to TypeScript as `unknown` — `serde_json::Value` carries
	 *  arbitrary JSON and specta will not emit its BigInt-bearing `Number`.
	 */
	details: unknown,
};

/**  Reply from [`ping`]. Proves the Rust↔TS seam and version wiring are live. */
export type Pong = {
	/**  Greeting echoing the caller's `name`. */
	message: string,
	/**  The running backend's crate version (`CARGO_PKG_VERSION`). */
	version: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

