// @generated by tauri-specta — run `just bindings` to regenerate.
/* eslint-disable */
// prettier-ignore

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Liveness check. Returns a greeting plus the backend version.
	 * 
	 *  `name` is rejected when blank so the frontend has a real error path to render
	 *  against before any milestone-1 command exists.
	 */
	ping: (name: string) => typedError<Pong, IpcError>(__TAURI_INVOKE("ping", { name })),
	/**
	 *  The real component catalog, merged with real installed state — what the Dependencies screen
	 *  renders.
	 */
	listComponents: () => typedError<ComponentInfo[], IpcError>(__TAURI_INVOKE("list_components")),
	/**
	 *  Run the real `bootstrap()` (task 0012) for every M1 component still missing, reporting
	 *  progress on `job://bootstrap` as it goes.
	 */
	bootstrapToolchain: () => typedError<null, IpcError>(__TAURI_INVOKE("bootstrap_toolchain")),
	/**  Every Google device profile, parsed from the installed `sdklib` jar. */
	listDevices: () => typedError<DeviceInfo[], IpcError>(__TAURI_INVOKE("list_devices")),
	/**
	 *  Today's real system-image catalog (Google's per-tag `sys-img2-3.xml` manifests), merged with
	 *  local install state.
	 */
	listImages: () => typedError<ImageInfo[], IpcError>(__TAURI_INVOKE("list_images")),
	/**  Every registry-tracked emulator with its live state — what the Dashboard polls. */
	listEmulators: () => typedError<EmulatorInfo[], IpcError>(__TAURI_INVOKE("list_emulators")),
	/**
	 *  Reconcile the registry against on-disk / adb reality, then return the refreshed list. The
	 *  Dashboard's "Refresh" action and a manual recovery from drift.
	 */
	reconcileNow: () => typedError<EmulatorInfo[], IpcError>(__TAURI_INVOKE("reconcile_now")),
	/**
	 *  Ensure the chosen image is installed, create the AVD, optionally launch it. Streams progress
	 *  on `job://emulator` with `jobId` `create:<avdName>`. Returns the new tracked id.
	 */
	createEmulator: (request: CreateEmulatorRequest) => typedError<string, IpcError>(__TAURI_INVOKE("create_emulator", { request })),
	/**
	 *  Launch an already-created emulator and wait for it to boot. Streams on `job://emulator` with
	 *  `jobId` `launch:<id>`.
	 */
	launchEmulator: (id: string) => typedError<null, IpcError>(__TAURI_INVOKE("launch_emulator", { id })),
	/**
	 *  Stop a running emulator: graceful `adb emu kill`, then force-kill the held child if it doesn't
	 *  exit (the shared provider means that held handle now actually persists — task 0020).
	 */
	stopEmulator: (id: string) => typedError<null, IpcError>(__TAURI_INVOKE("stop_emulator", { id })),
	/**  Rename a tracked emulator (display name only — the on-disk AVD name never changes). */
	renameEmulator: (id: string, displayName: string) => typedError<null, IpcError>(__TAURI_INVOKE("rename_emulator", { id, displayName })),
	/**
	 *  Update an emulator's stored RAM / storage / graphics. Recorded now; applied when the AVD is next
	 *  (re)created — see `AndroidProvider::set_hardware`.
	 */
	editHardware: (id: string, ramMb: number, storageMb: number, graphics: string) => typedError<null, IpcError>(__TAURI_INVOKE("edit_hardware", { id, ramMb, storageMb, graphics })),
	/**
	 *  Delete a tracked emulator. `wipe` also removes the AVD from disk (`avdmanager delete avd`);
	 *  `wipe = false` just untracks it.
	 */
	deleteEmulator: (id: string, wipe: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("delete_emulator", { id, wipe })),
	/**
	 *  Wipe an emulator's user data (deletes the AVD's writable images + snapshots; next launch
	 *  rebuilds them). Refuses while running.
	 */
	wipeEmulatorData: (id: string) => typedError<null, IpcError>(__TAURI_INVOKE("wipe_emulator_data", { id })),
	/**  Full detail for one emulator — its stored config plus live run state. */
	emulatorDetail: (id: string) => typedError<EmulatorDetail, IpcError>(__TAURI_INVOKE("emulator_detail", { id })),
	/**  Reveal a path in the OS file manager (Finder / Explorer / the default file browser). */
	revealPath: (path: string) => typedError<null, IpcError>(__TAURI_INVOKE("reveal_path", { path })),
};

/** Events */
export const events = {
	jobBootstrap: makeEvent<BootstrapProgress>("job://bootstrap"),
	jobEmulator: makeEvent<EmulatorJob>("job://emulator"),
};

/* Types */
/**  Live progress for a `bootstrap_toolchain` run, emitted as `job://bootstrap`. */
export type BootstrapProgress = {
	/**
	 *  Always [`JOB_ID`] today — carried on the payload anyway so the frontend never has to know
	 *  that, and so a future real job registry is a backward-compatible change, not a breaking one.
	 */
	jobId: string,
	payload: BootstrapProgressKind,
};

/**
 *  One update from a `bootstrap_toolchain` run. Mirrors `docs/architecture.md` §4's
 *  `job://progress`/`job://log`/`job://done` shapes, collapsed into one typed event (there is only
 *  ever one toolchain-bootstrap job at a time — a real per-job registry is M3's "Registry &
 *  reliable tracking" milestone, not needed here).
 */
export type BootstrapProgressKind = 
/**  A phase and/or percentage update. */
{ type: "progress"; phase: string | null; pct: number | null } | 
/**  One log line to append to the run's tail. */
{ type: "log"; line: string } | 
/**  The job reached a terminal state. */
{ type: "done"; ok: boolean; error: IpcError | null };

/**
 *  One component as shown on the Dependencies screen: catalog info merged with real install
 *  state (`installed`/`source` come from `emu_core::toolchain::InstalledState`, scanned fresh on
 *  every call — never cached, per the same rule `SystemImage::installed` follows).
 */
export type ComponentInfo = {
	/**  The exact `sdkmanager` package path (`ComponentId::repo_path`) — a stable id. */
	id: string,
	/**  Human-readable label for the UI. */
	name: string,
	/**  Package revision from the catalog. */
	version: string,
	/**
	 *  Archive size in bytes. `u32` (not the catalog's `u64`) because specta-typescript refuses
	 *  to export a bigint-risking `u64` to a plain JS `number` — every real M1 archive is well
	 *  under 4 GiB, and even `docs/spec.md`'s largest future system images (~3.5 GB) fit, so this
	 *  is a safe, deliberate narrowing, saturating at `u32::MAX` in the (currently impossible)
	 *  case of something bigger.
	 */
	sizeBytes: number,
	/**  Whether it's installed anywhere (the app's managed `sdk/` dir, or an existing system SDK). */
	installed: boolean,
	/**  Where it was found — `"app-managed"` or `"system:<path>"` — `None` when not installed. */
	source: string | null,
};

/**  Request body for [`create_emulator`]. */
export type CreateEmulatorRequest = {
	/**  Display name; the on-disk AVD name is a sanitized version of it. */
	name: string,
	/**  `DeviceInfo.id`. */
	deviceId: string,
	/**  `ImageInfo.coord`. */
	imageCoord: string,
	ramMb: number,
	storageMb: number,
	/**  Also launch it once created ("Create & launch"). */
	launch: boolean,
};

/**  A hardware profile for the Create wizard's device step. */
export type DeviceInfo = {
	/**  `avdmanager -d` id, e.g. `pixel_6`. */
	id: string,
	/**  Human name, e.g. `Pixel 6`. */
	name: string,
	/**  Manufacturer label; empty when unknown. */
	oem: string,
	/**  `phone` / `tablet` / `foldable` / `wear` / `tv` / `automotive` / `desktop`. */
	formFactor: string,
	/**  Manufacturer-recommended RAM in MiB. */
	ramMb: number,
	/**  `"<width> × <height>"` in pixels. */
	resolution: string,
	/**  Screen density in dpi. */
	densityDpi: number,
	/**  Physical diagonal in inches. */
	diagonalIn: number | null,
};

/**  Full config + live state for the detail panel. */
export type EmulatorDetail = {
	id: string,
	avdName: string,
	displayName: string,
	deviceProfileId: string,
	/**  `sdkmanager` package path, when known. */
	imageCoord: string | null,
	/**  Android API level from the image coord, when known. */
	api: number | null,
	hasPlayStore: boolean,
	ramMb: number,
	storageMb: number,
	/**  `auto` / `host` / `swiftshader`. */
	graphics: string,
	/**  `created here` / `adopted` / `from profile` / `imported`. */
	source: string,
	/**  Live: `stopped` / `booting` / `running` / `error`. */
	state: string,
	adbSerial: string | null,
	/**  RFC 3339. */
	createdAt: string,
	/**  RFC 3339. */
	updatedAt: string,
	/**  `<avd home>/<avd_name>.avd`, for the "Open folder" button. `None` if the home can't be resolved. */
	avdPath: string | null,
};

/**  A tracked emulator plus its live run state. */
export type EmulatorInfo = {
	id: string,
	avdName: string,
	displayName: string,
	/**  `stopped` / `booting` / `running` / `error`. */
	state: string,
	adbSerial: string | null,
};

/**  Live progress for an emulator create/launch run, emitted as `job://emulator`. */
export type EmulatorJob = {
	/**  `create:<avdName>` or `launch:<id>` — the frontend filters its progress panel by this. */
	jobId: string,
	payload: EmulatorJobKind,
};

/**
 *  One update from a `create_emulator`/`launch_emulator` run. Same tagged shape as
 *  `toolchain::BootstrapProgressKind` (`docs/architecture.md` §4's `job://*` events, collapsed);
 *  the `jobId` on [`EmulatorJob`] says which run it belongs to.
 */
export type EmulatorJobKind = 
/**  A phase and/or percentage update. */
{ type: "progress"; phase: string | null; pct: number | null } | 
/**  One log line to append to the run's tail. */
{ type: "log"; line: string } | 
/**  The run reached a terminal state. */
{ type: "done"; ok: boolean; error: IpcError | null };

/**  A system image for the Create wizard's image step. */
export type ImageInfo = {
	/**  `sdkmanager` package path — the id passed back to `create_emulator`. */
	coord: string,
	/**  Android API level. */
	api: number,
	/**  Marketing Android version, e.g. `"14"`. */
	androidVersion: string,
	/**  `default` / `google_apis` / `google_apis_playstore` / … */
	imageType: string,
	/**  `x86_64` / `arm64-v8a` / … */
	abi: string,
	/**  Package revision. */
	revision: string,
	/**
	 *  Archive size in bytes — `u32` (specta won't export a bigint-risking `u64`; every real
	 *  image is well under 4 GiB), saturating.
	 */
	downloadSizeBytes: number,
	/**  Whether it's already installed in the managed SDK. */
	installed: boolean,
	/**  Whether it bundles the Play Store. */
	hasPlayStore: boolean,
};

/**  Serializable error surfaced to the frontend across the typed IPC seam. */
export type IpcError = {
	/**
	 *  Stable machine-readable code, e.g. `not_found`, `process_failed`.
	 *  Sourced from [`emu_core::CoreError::code`] when the origin is a core error.
	 */
	code: string,
	/**  Human-facing description of what went wrong and, where possible, what to do. */
	message: string,
	/**
	 *  Optional structured context (paths, exit codes, offending values).
	 *  Exported to TypeScript as `unknown` — `serde_json::Value` carries
	 *  arbitrary JSON and specta will not emit its BigInt-bearing `Number`.
	 */
	details: unknown,
};

/**  Reply from [`ping`]. Proves the Rust↔TS seam and version wiring are live. */
export type Pong = {
	/**  Greeting echoing the caller's `name`. */
	message: string,
	/**  The running backend's crate version (`CARGO_PKG_VERSION`). */
	version: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

