//! EmuManager Tauri shell.
//!
//! This crate is **glue only** — Tauri commands, event emitters, and dependency
//! wiring. All domain logic lives in `emu-core` and the provider crates
//! (`AGENTS.md` §6, `docs/architecture.md` §2).
//!
//! The Rust↔TS seam is typed: [`specta_builder`] registers every command with
//! `tauri-specta`, which the `export_bindings` test renders into
//! `src/lib/bindings.ts` (`just bindings`). Never hand-edit that file.

#![deny(unsafe_code)]

mod commands;
mod ipc_error;
mod ports;

use tauri_specta::{collect_commands, Builder};

pub use commands::Pong;
pub use ipc_error::IpcError;

/// The single `tauri-specta` builder — the source of truth for the IPC surface.
///
/// `run()` mounts it on the real Tauri app; the `export_bindings` test renders
/// it to TypeScript. Both call this so the generated bindings can never drift
/// from what the app actually serves.
fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new().commands(collect_commands![commands::ping])
}

/// Build and run the desktop application.
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = specta_builder();

    tauri::Builder::default()
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running the EmuManager application");
}

#[cfg(test)]
mod export {
    use super::specta_builder;
    use specta_typescript::Typescript;

    /// Regenerate `src/lib/bindings.ts`. Run via `just bindings`; CI asserts the
    /// checked-in file matches (`git diff --exit-code src/lib/bindings.ts`).
    #[test]
    fn export_bindings() {
        let header = "\
// @generated by tauri-specta — run `just bindings` to regenerate.
/* eslint-disable */
// prettier-ignore
";
        specta_builder()
            .export(
                Typescript::default().header(header),
                "../src/lib/bindings.ts",
            )
            .expect("failed to export TypeScript bindings");
    }
}
